version: '3.2'

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
      - '29094:29094'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=EXTERNAL://0.0.0.0:9092,INTERNAL://kafka:29094
      - KAFKA_CFG_ADVERTISED_LISTENERS=EXTERNAL://127.0.0.1:9092,INTERNAL://kafka:29094
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ADVERTISED_HOST_NAME=host.docker.internal 
    depends_on:
      - zookeeper
      - eureka-server
      
  account-processor:
    build: ./account-processor 
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka     
    depends_on:
      - kafka
      - zuul-server
      
  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"

  zuul-server:
    build: ./zuul-server
    ports:
      - "80:80"
    depends_on:
      - eureka-server
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka     

  account-service:
    build: ./account-service
    ports:
      - "8000:8000"
    depends_on:
      - eureka-server
      - zuul-server
      - kafka
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka     

  rest1-server:
    build: ./rest1-server
    ports:
      - "9001:9001"
    depends_on:
      - eureka-server
      - zuul-server
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka


  rest2-server:
    build: ./rest2-server
    ports:
      - "9002:9002"
    depends_on:
      - eureka-server
      - zuul-server
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka