server:
  port: 8000

spring:
  application:
    name: account-service
  zipkin:
    enabled: true
    base-url: ${ZIPKIN_URL:http://zipkin:9411}/

bootstrap:
   servers: kafka:29094    

management:
  endpoints:
    web:
      exposure:
        include: 
         - "prometheus"
         - "health"  
         - "info"

# HEALTH ENDPOINT
# enable a detailed view
#http://localhost:port/actuator/health
  endpoint:
     health:
       show-details: always

  metrics:
    tags:
      application: ${spring.application.name}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}:${random.value}}